Loa 324 check player location for accepting quest
TheLaendOfAdventure/The-Laend-of-Adventure pull request #110
Opened 2023-06-13 16:33 UTC by ayal104

2023-06-13 19:44 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
> +    suspend fun getCurrentLocation(questID: Int, callback: (Boolean) -> Unit) {
Please use a suitable name for the function

2023-06-13 19:44 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
> +                println("Failed to get location: ${e.message}")
Please use a log instead of a println

2023-06-13 19:44 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
> +                    println("Is current location matching the target location? $isMatchingLocation")
Please remove println or change it to log, but I would prefer to log the boolean inside TrackingLogic.

2023-06-13 19:45 UTC, DorinaSobiecki requested changes
See comments above

2023-06-14 14:26 UTC, ayal104 commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
> +                println("Failed to get location: ${e.message}")
Changed it in the new commit :)

2023-06-14 14:26 UTC, ayal104 commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
> +                    println("Is current location matching the target location? $isMatchingLocation")
Changed it to log and moved it to TrackingLogic into the isUserAtQuestLocation function.

2023-06-15 20:55 UTC, DorinaSobiecki approved these changes
![](https://media4.giphy.com/media/l0HlCSRTZIlN2WJfW/200w.webp?cid=ecf05e474zgu6yuyafs55dai7fm8cm735wuu1p9j6nmj5tzu&ep=v1_gifs_search&rid=200w.webp&ct=g)
LGTM

2023-06-16 10:39 UTC, merged