Loa 398 json reader testing
TheLaendOfAdventure/The-Laend-of-Adventure pull request #119
Opened 2023-06-15 16:08 UTC by SebastianMaier03

2023-06-18 20:27 UTC, DorinaSobiecki requested changes

2023-06-18 20:27 UTC, DorinaSobiecki commented on app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelperTest.kt
> +    fun readNpcNameFromJsonFile_ExistingNpcName_ReturnsNpcName() {
In my opinion all function names are a bit too long, maybe something like
I don't think it is necessary to specify the expected return within the function name.

2023-06-18 20:32 UTC, SebastianMaier03 commented on app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelperTest.kt
> +    fun readNpcNameFromJsonFile_ExistingNpcName_ReturnsNpcName() {
All tests should be named like this to explain what is testet

2023-06-20 14:28 UTC, DorinaSobiecki approved these changes

2023-06-20 14:30 UTC, merged