LOA-354 Show uncompleted/completed badges combined in one recyclerview
TheLaendOfAdventure/The-Laend-of-Adventure pull request #123
Opened 2023-06-22 15:34 UTC by DorinaSobiecki

2023-06-22 19:46 UTC, JohannesHausch requested changes
See above

2023-06-22 19:46 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
>          // sets the text to the textview from our itemHolder class
These comments are unnecessary.

2023-06-22 19:46 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
>          val actionCompleted = badgeRepository.getCompletedGoalsForBadgeByUserID(
That's not a nice coding style, can't you use a ViewModel for that? 

Just pass the ViewModel in the constructor, so you can reach it from the adapter.

2023-06-22 19:46 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
> -        val userObserver = Observer<UserEntity> { user ->
Why don't you like the profile button?

2023-06-22 20:34 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
> -        val userObserver = Observer<UserEntity> { user ->
In Germany we say "Ein bisschen Schwund ist immer"

2023-06-22 22:48 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
>          val actionCompleted = badgeRepository.getCompletedGoalsForBadgeByUserID(
Just pass the ViewModel in the constructor, doesn't seem like nice coding either please check my solution and let me know what you think

2023-06-27 19:22 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/BadgesPageViewModel.kt
> +                val innerPair2 = Pair(uncompletedGoals.map { it }, false)
innerPair2 is a nondescript name.

2023-06-27 19:23 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/BadgesPageViewModel.kt
> +                val actionsPair = Pair(badge, listOf(innerPair, innerPair2))
Maybe a custom data class is better here.

2023-06-27 19:24 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
> +        val badgeObserver1 = Observer<List<Pair<BadgeDetails, List<Pair<List<String>, Boolean>>>>> { badgeList ->
Use custom data class.

2023-06-27 19:26 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
> +        val outer: View = itemView.findViewById(R.id.badge_outer)
Please use bindings instead of findViewById

2023-06-27 19:29 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
> +    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
The function has many lines. Can you outsource code parts to functions?

2023-06-27 19:29 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
> +        const val paddingBottom = 200
Does the value have to be public?

2023-06-29 12:06 UTC, JohannesHausch approved these changes
![](https://media1.giphy.com/media/aCdoGfL5ewBXEMan8r/giphy.gif?cid=ecf05e477euqsgaz50ztslnljcrdf06dk5d387k6tuzp40mt&ep=v1_gifs_gifId&rid=giphy.gif&ct=s)
Seems good

2023-06-29 12:11 UTC, merged