Loa 350 implement riddle popup styling
TheLaendOfAdventure/The-Laend-of-Adventure pull request #129
Opened 2023-06-27 22:14 UTC by Kostanix

2023-07-09 23:30 UTC, ayal104 requested changes
See comments :)

2023-07-09 23:30 UTC, ayal104 commented on app/src/main/res/layout/dialog_accept_quest_popup.xml
> +        android:layout_width="100dp"
Please fix the IDs.

2023-07-09 23:30 UTC, ayal104 commented on app/src/main/res/layout/dialog_accept_quest_popup.xml
> +            android:id="@+id/mainPage_profileButton"
Fix this ID as well.

2023-07-09 23:30 UTC, ayal104 commented on app/src/main/res/values/strings.xml
>      <string name="quest_accept">Accept</string>
Also maybe change Accept and Decline to German here.

2023-07-14 09:04 UTC, Kostanix commented on app/src/main/res/values/strings.xml
>      <string name="quest_accept">Accept</string>
Already did in another branch

2023-07-14 09:42 UTC, ayal104 approved these changes
![](https://media0.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif?cid=ecf05e47pw2zr4ddeu28vzqafsb2ck42ryh47mti4r07mtgn&ep=v1_gifs_search&rid=giphy.gif&ct=g)
LGTM

2023-07-14 09:43 UTC, merged