Loa 341 implement badge page styling
TheLaendOfAdventure/The-Laend-of-Adventure pull request #134
Opened 2023-06-29 12:55 UTC by Kostanix

2023-06-29 14:04 UTC, JohannesHausch requested changes
The green of the progressbar hurts in my eyes. Can you please change that?

2023-06-29 14:07 UTC, ayal104 requested changes

2023-06-29 14:07 UTC, ayal104 commented on app/src/main/res/layout/fragment_badges_page.xml
> +                android:scaleType="center"
Why is the content description image_frame?

2023-06-29 14:16 UTC, JohannesHausch commented
The space between the icons and the bath name is too small.

2023-07-07 13:41 UTC, Kostanix commented on app/src/main/res/layout/fragment_badges_page.xml
> +                android:scaleType="center"
Because it is just a image frame, vut I changed the name now

2023-07-14 11:20 UTC, ayal104 approved these changes
LGTM!

2023-07-14 11:21 UTC, JohannesHausch approved these changes
LGTM!

2023-07-14 11:25 UTC, merged