Create main_page.xml and drawable files
TheLaendOfAdventure/The-Laend-of-Adventure pull request #26
Opened 2023-05-03 18:11 UTC by JohannesHausch

2023-05-04 21:58 UTC, DorinaSobiecki requested changes

2023-05-04 21:58 UTC, DorinaSobiecki commented on app/src/main/res/layout/main_page.xml
Bitte einmal die ID's entsprechend anpassen
Für "preview Texte" würde ich tools:text anstelle von android:text nehmen

2023-05-06 21:36 UTC, DorinaSobiecki requested changes

2023-05-06 21:36 UTC, DorinaSobiecki commented on app/src/main/res/values/strings.xml
Please change the language from mainPage_profileButton and mainPage_compass to German

2023-05-06 23:49 UTC, Kostanix commented on app/src/main/res/values/strings.xml
I need further explanation

2023-05-08 00:50 UTC, DorinaSobiecki approved these changes
Lgtm ![](https://i.giphy.com/media/cfuL5gqFDreXxkWQ4o/giphy.webp)

2023-05-08 08:41 UTC, merged