Loa 202 quest page
TheLaendOfAdventure/The-Laend-of-Adventure pull request #32
Opened 2023-05-06 22:48 UTC by Kostanix

2023-05-07 11:12 UTC, DorinaSobiecki requested changes
use list / list adapter to show all quest dynamically

2023-05-07 11:12 UTC, DorinaSobiecki commented on app/src/main/res/layout/quest_page.xml
Please have a look at this 
https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter

2023-05-18 14:53 UTC, DorinaSobiecki requested changes

2023-05-18 14:53 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/QuestPageViewModel.kt
> +    val badges = questRepository.getUnacceptedQuestsByUserID(userID).asLiveData()
Please change it to val badges = questRepository.getAcceptedQuestsByUserID(userID).asLiveData()

2023-05-18 20:19 UTC, Kostanix commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/QuestPageViewModel.kt
> +    val badges = questRepository.getUnacceptedQuestsByUserID(userID).asLiveData()
done

2023-05-18 22:17 UTC, JohannesHausch requested changes
Please check out the comments!

2023-05-18 22:17 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/QuestPageFragment.kt
> +                R.id.navigate_from_quest_to_main_page
Something is going mighty wrong here?

You call something with pages but refer to the main page?

2023-05-18 22:17 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/QuestPageFragment.kt
> +        }
Why are 2 buttons bound here and only one button in the other function? 

Either you bind each button in a single function or all together in one function.

2023-05-18 22:17 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/UserPageViewModel.kt
>          userRepository.updateUserImagePath(userID, imagePath)
I really like how you apply the multi-threading here, it would be desirable if this would happen in the other ViewModels too. 

That would make me happy.
![](https://media2.giphy.com/media/Ss9mDNNWskylCyh1Xh/giphy.gif?cid=ecf05e47qpot6cmicnfysdsiqt4vd221ivuvcdb9vj32t21e&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2023-05-18 23:13 UTC, Kostanix commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
> +class BadgesAdapter(private val badgeList: List<BadgeEntity>) : RecyclerView.Adapter<BadgesAdapter.ViewHolder>() { // ktlint-disable max-line-length
done

2023-05-18 23:14 UTC, Kostanix commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/QuestPageFragment.kt
> +        viewModel.questList.observe(viewLifecycleOwner, questObserver)
Done.

2023-05-18 23:16 UTC, Kostanix commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/QuestPageFragment.kt
> +                R.id.navigate_from_quest_to_main_page
Bad method name indeed, fixed.

2023-05-18 23:18 UTC, Kostanix commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/QuestPageFragment.kt
> +        }
We already had this discussion and decided to bunch the navigation buttons together.

2023-05-18 23:28 UTC, Kostanix commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/UserPageViewModel.kt
>          userRepository.updateUserImagePath(userID, imagePath)
I understand your concern, but observers are supposed to run on the main thread. I ask for your understanding.

2023-05-18 23:32 UTC, JohannesHausch approved these changes
LGTM!

![](https://media3.giphy.com/media/JQRmrkugwVwI3JbH4n/giphy.gif?cid=ecf05e47gdmmzrudec8kfqho64mwuy0wgn8ad3r4j7wzjok5&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2023-05-18 23:33 UTC, DorinaSobiecki approved these changes
lgtm

2023-05-18 23:34 UTC, merged