LOA-255 Add 1 Quest with conversations etc.
TheLaendOfAdventure/The-Laend-of-Adventure pull request #43
Opened 2023-05-15 17:37 UTC by SebastianMaier03

2023-05-15 19:44 UTC, JohannesHausch requested changes

2023-05-15 19:44 UTC, JohannesHausch commented on app/src/main/assets/Conversations/BrückenTrollRiddle.json
> +			"message": "Hallo, ich möchte die Wackelbrücke überqueren, um meine Stärke zu Beweisen. Darf ich passieren?"
Can you please add a line break to make the question more meaningful?

2023-05-16 06:01 UTC, SebastianMaier03 commented on app/src/main/assets/Conversations/BrückenTrollRiddle.json
> +			"message": "Hallo, ich möchte die Wackelbrücke überqueren, um meine Stärke zu Beweisen. Darf ich passieren?"
yes

2023-05-16 10:41 UTC, JohannesHausch approved these changes
![](https://media1.giphy.com/media/3o75279fBGgbO848ZW/giphy.gif?cid=ecf05e476n27oadaevgytq4f5hq6w04c6x7k9so92hkapzph&ep=v1_gifs_search&rid=giphy.gif&ct=g)

LGTM!

2023-05-16 10:42 UTC, merged