Loa 317 add conversation popup
TheLaendOfAdventure/The-Laend-of-Adventure pull request #79
Opened 2023-05-26 11:17 UTC by JohannesHausch

2023-05-26 15:30 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/ActionDao.kt
> +        "SELECT  dialogPath FROM [action] " +
Remove second whitespace

2023-05-26 15:37 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
> +        }
Why is the first checkRiddle() inside a CoroutineScope and the one inside the else not?
Maybe just call the checkRiddle() after the if and remove the else.

2023-05-26 15:48 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
> +            "FROM [action] " +
This will cause the error java.lang.IllegalArgumentException: There is no table with name [action]

2023-05-26 15:48 UTC, DorinaSobiecki requested changes
See above

2023-05-26 15:57 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/ActionDao.kt
> +        "SELECT  dialogPath FROM [action] " +
Is fixed in the next commit.

2023-05-26 16:03 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
> +        }
Because of withContext(Dispatchers.Main) we are on the main thread (remember to show UI, you have to use Main-Thread) and the checkRiddle function is a suspend function and thus is not allowed to be called from the main thread.
So I opened an IO thread and called the function. 

CheckRiddle has to be called there because it depends on closing the conversation popup. That's why it's inside the OnDismissListener.

2023-05-26 16:09 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
> +            "FROM [action] " +
Can you send proof for the exception I cannot replicate the error?

2023-05-26 16:27 UTC, DorinaSobiecki commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
> +            "FROM [action] " +
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.hdmstuttgart.the_laend_of_adventure, PID: 18943
    java.lang.IllegalArgumentException: There is no table with name [action]
        at androidx.room.InvalidationTracker.addObserver(InvalidationTracker.kt:253)
        at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

2023-05-28 13:25 UTC, SebastianMaier03 commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
> +            "FROM [action] " +
I got the same Error

2023-05-28 18:14 UTC, JohannesHausch commented on app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
> +            "FROM [action] " +
Fixed in the last commit!

2023-05-28 18:46 UTC, DorinaSobiecki approved these changes
![](https://media2.giphy.com/media/ynyFryHnkbHeYN58xp/giphy.gif?cid=ecf05e47b0320097f6d57dbb989beafe8542b7d013008f6f&ep=v1_gifs_gifId&rid=giphy.gif&ct=g)
LGTM

2023-05-29 07:49 UTC, merged